### ISSUE TITLE
If there is no docs at all play-swagger throws 

### ISSUE THREAD

**Issue by kailuowang** [iheartradio/play-swagger#105]
`java.lang.UnsupportedOperationException: empty.reduceLeft`

**Comment by softinio** [comment]
Is there a workaround for this?

**Comment by JacopoGobbi** [comment]
```
[myproj] $ swagger
[info] Compiling 7 Scala sources and 1 Java source to /{{myprojdir}}/target/scala-2.12/classes ...
[info] Done compiling.
[info] Running com.iheart.playSwagger.SwaggerSpecRunner /{{myprojdir}}/target/swagger/swagger.json routes models  false 1.0
[error] (run-main-2) java.lang.UnsupportedOperationException: empty.reduceLeft
[error] java.lang.UnsupportedOperationException: empty.reduceLeft
[error] 	at scala.collection.TraversableOnce.reduceLeft(TraversableOnce.scala:180)
[error] 	at scala.collection.TraversableOnce.reduceLeft$(TraversableOnce.scala:178)
[error] 	at scala.collection.AbstractTraversable.reduceLeft(Traversable.scala:104)
[error] 	at scala.collection.TraversableOnce.reduce(TraversableOnce.scala:208)
[error] 	at scala.collection.TraversableOnce.reduce$(TraversableOnce.scala:208)
[error] 	at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.generateWithBase(SwaggerSpecGenerator.scala:132)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutes(SwaggerSpecGenerator.scala:126)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutesFile$16(SwaggerSpecGenerator.scala:106)
[error] 	at scala.util.Success.flatMap(Try.scala:247)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutesFile(SwaggerSpecGenerator.scala:105)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:50)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:28)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:31)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:7)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:7)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$12(SwaggerPlugin.scala:47)
[error] 	at scala.util.Success.foreach(Try.scala:249)
[error] 	at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$11(SwaggerPlugin.scala:47)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (swagger) Nonzero exit code: 1
[error] Total time: 3 s, completed 23-Jun-2018 16:09:19
```
Only workaround at the moment is to create a doc at an endpoint

**Comment by romeromfm** [comment]
I'm facing the same issue here. Any news?

**Comment by BartekH** [comment]
Facing the same problem, any update?
