### ISSUE TITLE
Support sbt ~run

### ISSUE THREAD

**Issue by kindlychung** [iheartradio/play-swagger#148]
Automatic regeneration of documentation would be awesome.

**Comment by kailuowang** [comment]
hmm, you use `~run` with you Play application?

**Comment by kindlychung** [comment]
Yeah, is there anything wrong with it?

**Comment by ultrasonex** [comment]
I am trying to run using `sbt run` to the run the application in dev env after adding the corresponding plugins mentioned in the doc. But it is erroring out  with the below stack trace . 

```[error] (run-main-0) com.iheart.playSwagger.SwaggerSpecGenerator$MissingBaseSpecException$: Missing a swagger.yml or swagger.json to provide base swagger spec
com.iheart.playSwagger.SwaggerSpecGenerator$MissingBaseSpecException$: Missing a swagger.yml or swagger.json to provide base swagger spec
        at com.iheart.playSwagger.SwaggerSpecGenerator$MissingBaseSpecException$.<clinit>(SwaggerSpecGenerator.scala)
        at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$defaultBase$1(SwaggerSpecGenerator.scala:236)
        at scala.Option.getOrElse(Option.scala:121)
        at com.iheart.playSwagger.SwaggerSpecGenerator.defaultBase$lzycompute(SwaggerSpecGenerator.scala:236)
        at com.iheart.playSwagger.SwaggerSpecGenerator.defaultBase(SwaggerSpecGenerator.scala:236)
        at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:43)
        at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:23)
        at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:26)
        at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:7)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:7)
        at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.Run.invokeMain(Run.scala:67)
        at sbt.Run.run0(Run.scala:61)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2135)
        at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2135)
        at scala.Option.foreach(Option.scala:236)
        at sbt.BuildCommon$class.toError(Defaults.scala:2135)
        at sbt.package$.toError(package.scala:4)
        at com.iheart.sbtPlaySwagger.SwaggerPlugin$$anonfun$projectSettings$9.apply(SwaggerPlugin.scala:41)
        at com.iheart.sbtPlaySwagger.SwaggerPlugin$$anonfun$projectSettings$9.apply(SwaggerPlugin.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (*:swagger) Nonzero exit code: 1
[error] Total time: 1 s, completed Aug 7, 2017 4:08:02 PM
```

Is there anything I am missing ? 

Steps 1> Added Pluggin - ```
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.1")

//Ebean ORM Plugin
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "4.0.2")

// play swagger plugin
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.6.1-PLAY2.6")


// web plugins

addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.3")

addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.7")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.1.0")

addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.2")
```  and enabled plugin in built.sbt 

```lazy val root = (project in file(".")).enablePlugins(PlayScala,PlayEbean,SwaggerPlugin)```
also added  ```"org.webjars"            %  "swagger-ui"         % "3.0.8" ``` as a dependency .   Am I missing something ?
