### ISSUE TITLE
Reflection fails: Scala 2.12, Play 2.6 with url segment variables

### ISSUE THREAD

**Issue by p4ndaman** [iheartradio/play-swagger#168]
My `routes` file has an endpoint with a variable referenced in the url pattern
```
GET /endpoint/:resource controllers.HomeController.endpoint(resource)
```

I see that generated Routes class has an entry in the list returned by `def documentation`:
```
("""GET""", this.prefix + (if(this.prefix.endsWith("/")) "" else "/") + """endpoint/""" + "$" + """resource<[^/]+>""", """controllers.HomeController.endpoint(resource:String)""")
```

Running `sbt swagger` results in an exception resolving the class for `resource`:
```
[info] Running com.iheart.playSwagger.SwaggerSpecRunner /Users/mayur.pandya/code/tungsten-model-manager/target/swagger/swagger.json routes
[error] (run-main-0) scala.ScalaReflectionException: class String not found.
scala.ScalaReflectionException: class String not found.
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:122)
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:22)
	at com.iheart.playSwagger.DefinitionGenerator.definition(DefinitionGenerator.scala:44)
	at com.iheart.playSwagger.DefinitionGenerator.allReferredDefs$1(DefinitionGenerator.scala:57)
	at com.iheart.playSwagger.DefinitionGenerator.$anonfun$allDefinitions$8(DefinitionGenerator.scala:71)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at com.iheart.playSwagger.DefinitionGenerator.allDefinitions(DefinitionGenerator.scala:70)
	at com.iheart.playSwagger.SwaggerSpecGenerator.generateWithBase(SwaggerSpecGenerator.scala:137)
	at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutes(SwaggerSpecGenerator.scala:119)
	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutesFile$16(SwaggerSpecGenerator.scala:99)
	at scala.util.Success.flatMap(Try.scala:247)
	at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutesFile(SwaggerSpecGenerator.scala:98)
	at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:43)
	at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:23)
	at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:26)
	at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:7)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:7)
	at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
```
Removing this endpoint (keeping only endpoints without url pattern variables) yields a successful swagger.json.

Here's what's relevant in `plugins.sbt`:
```
resolvers += Resolver.bintrayRepo("iheartradio", "maven")
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.6.1-PLAY2.6")
```

And in `build.sbt`
```
resolvers += Resolver.bintrayRepo("iheartradio", "maven")
libraryDependencies += "com.iheart" %% "play-swagger" % "0.6.1-PLAY2.6"
```
My root project Scala version 2.12.2. My immediate suspicion is that because the sbt-play-swagger plugin is compiled for 2.10, it cannot use reflection to load a class during runtime for a later version of Scala. However, the reflection code is being called by `com.iheart.playSwagger.DefinitionGenerator` from the play-swagger jar - this should be a 2.12 dependency. I've even tried `dependencyOverrides += "com.iheart" %% "play-swagger" % "0.6.1-PLAY2.6"` in `build.sbt` just in case.

Am I missing something? Is there a workaround? Are there any plans to support the plugin for 2.12?
Thanks!

**Comment by kailuowang** [comment]
The plugin is calling the 2.12 jar to generate the swagger file. What is your `swaggerDomainNameSpaces := ???` in your build.sbt?

**Comment by p4ndaman** [comment]
I do not have anything defined for `swaggerDomainNameSpaces` right now. Am I right to assume this is optional?

**Comment by kailuowang** [comment]
hmmm, this shouldn't be optional. For now please add a setting (say "models" ) and see if it helps.

**Comment by p4ndaman** [comment]
That did the trick! Not sure how though. Thank you!
