### ISSUE TITLE
Exception when using an optional default value of "0L" in a route

### ISSUE THREAD

**Issue by alvaroc1** [iheartradio/play-swagger#175]
routes file:
```
...
GET            /page.html                   @controllers.Front.page(invitationId: Long ?= 0L)
```
Exception:
```
[error] (run-main-2) java.lang.NumberFormatException: For input string: "0L"
java.lang.NumberFormatException: For input string: "0L"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:276)
	at scala.collection.immutable.StringOps.toLong(StringOps.scala:29)
	at com.iheart.playSwagger.SwaggerParameterMapper$$anonfun$7.apply(SwaggerParameterMapper.scala:34)
	at com.iheart.playSwagger.SwaggerParameterMapper$$anonfun$7.apply(SwaggerParameterMapper.scala:32)
	at scala.Option.map(Option.scala:146)
	at com.iheart.playSwagger.SwaggerParameterMapper$.mapParam(SwaggerParameterMapper.scala:32)
	at com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$31$$anonfun$apply$23.apply(SwaggerSpecGenerator.scala:351)
	at com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$31$$anonfun$apply$23.apply(SwaggerSpecGenerator.scala:349)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
	at scala.collection.immutable.List.foreach(List.scala:381)
```

Workaround: Remove the "L" from the number on the routes file.

**Comment by Javakky-pxv** [comment]
@alvaroc1 
We are currently reviewing it. It may take some time, but we plan to address it.
