### ISSUE TITLE
Error occurs when using List[Option[Foo]]

### ISSUE THREAD

**Issue by ljwagerfield** [iheartradio/play-swagger#204]
sbt: `0.13.16`
scala: `2.12.2`
play: `2.6.5`
play-swagger: `0.6.2-PLAY2.6`

------

When using the following DTOs:

```
case class Foo(values: List[Option[Bar]])
object Foo { 
  implicit val jsonFormat = format[Foo] 
}

case class Bar(qux: String, baz: Int)
object Bar { 
  implicit val jsonFormat = format[Bar] 
  implicit val jsonFormatOpt = optionWithNull[Bar]
}
```

I receive the following error from `play-swagger`:
```
Execution exception[[ScalaReflectionException: class Bar] in JavaMirror with ReloadableClassLoader(v1){file:..... <long classpath> .....home/jre/classes] not found.]]
..... <play/akka stack frames only> ......
Caused by: scala.ScalaReflectionException: class Bar] in JavaMirror with ReloadableClassLoader(v1){file:...... <long classpath> .....home/jre/classes] not found.
  at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:122)
  at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:22)
  at com.iheart.playSwagger.DefinitionGenerator.definition(DefinitionGenerator.scala:44)
  at com.iheart.playSwagger.DefinitionGenerator.allReferredDefs$1(DefinitionGenerator.scala:57)
  at com.iheart.playSwagger.DefinitionGenerator.$anonfun$allDefinitions$7(DefinitionGenerator.scala:65)
  at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  at scala.collection.immutable.List.foldLeft(List.scala:86)
  at com.iheart.playSwagger.DefinitionGenerator.allReferredDefs$1(DefinitionGenerator.scala:64)
  at com.iheart.playSwagger.DefinitionGenerator.$anonfun$allDefinitions$7(DefinitionGenerator.scala:65)
  at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  at scala.collection.immutable.List.foldLeft(List.scala:86)
  at com.iheart.playSwagger.DefinitionGenerator.allReferredDefs$1(DefinitionGenerator.scala:64)
  at com.iheart.playSwagger.DefinitionGenerator.$anonfun$allDefinitions$8(DefinitionGenerator.scala:71)
  at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  at scala.collection.immutable.List.foldLeft(List.scala:86)
  at com.iheart.playSwagger.DefinitionGenerator.allDefinitions(DefinitionGenerator.scala:70)
  at com.iheart.playSwagger.SwaggerSpecGenerator.generateWithBase(SwaggerSpecGenerator.scala:137)
  at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutes(SwaggerSpecGenerator.scala:119)
  at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutesFile$16(SwaggerSpecGenerator.scala:99)
  at scala.util.Success.flatMap(Try.scala:247)
  at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutesFile(SwaggerSpecGenerator.scala:98)
  at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:43)
  at com.dynamicip.api.common.swagger.SwaggerController.$anonfun$swaggerFile$1(SwaggerController.scala:18)
  at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
  at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
  at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
  at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
  at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
  at scala.util.Try$.apply(Try.scala:209)
  at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
  at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
  at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
  ... 27 common frames omitted
```

Is this a known limitation?

The motivation behind using `List[Option[Foo]]` is to support lists with null elements.

**Comment by kailuowang** [comment]
It's complaining another class is not found...

**Comment by ljwagerfield** [comment]
My apologies -- stack trace updated.

**Comment by kailuowang** [comment]
Okay. I think this is a known issue. You will have to write your own custom type definition for `List[Option[Bar]]`

**Comment by ljwagerfield** [comment]
Please could you provide an example?

**Comment by kailuowang** [comment]
https://github.com/iheartradio/play-swagger#how-to-override-type-mappings

**Comment by akalinovskiy** [comment]
I've faced with the same issue, try to define swagger-custom-mappings.yml as
```
---
  - type: models\.MyType\]
    specAsParameter: []   #this hides the type from query and path parameter
    specAsProperty:
      type: "array"
      items:
        $ref: "#/components/schemas/models.MyType"
```
It works for me
