### ISSUE TITLE
play-swagger crashes  for play 2.6 scala 2.12

### ISSUE THREAD

**Issue by yurir** [iheartradio/play-swagger#215]
```
[info] Running com.iheart.playSwagger.SwaggerSpecRunner /Users/yurironin/git/Eagle-2.6/target/swagger/swagger.json routes com.clarizen.model.api  false
[error] (run-main-0) java.lang.NumberFormatException: For input string: "null"
[error] java.lang.NumberFormatException: For input string: "null"
[error] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[error] 	at java.lang.Long.parseLong(Long.java:589)
[error] 	at java.lang.Long.parseLong(Long.java:631)
[error] 	at scala.collection.immutable.StringLike.toLong(StringLike.scala:306)
[error] 	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:306)
[error] 	at scala.collection.immutable.StringOps.toLong(StringOps.scala:29)
[error] 	at com.iheart.playSwagger.SwaggerParameterMapper$.$anonfun$mapParam$5(SwaggerParameterMapper.scala:33)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at com.iheart.playSwagger.SwaggerParameterMapper$.mapParam(SwaggerParameterMapper.scala:31)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$endPointSpec$4(SwaggerSpecGenerator.scala:364)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$endPointSpec$2(SwaggerSpecGenerator.scala:362)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.endPointSpec(SwaggerSpecGenerator.scala:361)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.endPointEntry(SwaggerSpecGenerator.scala:327)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$paths$1(SwaggerSpecGenerator.scala:303)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.paths(SwaggerSpecGenerator.scala:303)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutes$1(SwaggerSpecGenerator.scala:118)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutes(SwaggerSpecGenerator.scala:115)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutesFile$16(SwaggerSpecGenerator.scala:100)
[error] 	at scala.util.Success.flatMap(Try.scala:247)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutesFile(SwaggerSpecGenerator.scala:99)
[error] 	at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:45)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:27)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:30)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:7)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:7)
[error] 	at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:89)
[error] 	at sbt.Run.run0(Run.scala:83)
[error] 	at sbt.Run.execute$1(Run.scala:61)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:73)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$11(SwaggerPlugin.scala:45)
[error] 	at scala.util.Success.foreach(Try.scala:249)
[error] 	at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$10(SwaggerPlugin.scala:45)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (*:swagger) Nonzero exit code: 1

```

**Comment by kailuowang** [comment]
can you post your routes file here, I am guessing that you have a default value of "null" for a Int/Long type.

**Comment by yurir** [comment]
yes, you are right
`
DELETE        /projects/users                                                              controllers.ProjectsController.removeUser(userId: java.lang.Long ?= null)`

How can i overcome?

**Comment by kailuowang** [comment]
`Option` is your friend. null shouldn't really exist in the scala language, although it has to be there to support interop with Java. 
`userId: Option[Long]` is the recommended for optional parameters.

**Comment by yurir** [comment]
Thanks! Solved.

**Comment by Flo354** [comment]
I am late on this issue, but don't think it worth creating another one.

Play doc recommends using java.util.Optional for optional values: https://www.playframework.com/documentation/2.6.x/JavaRouting#Optional-parameters

Shouldn't play-swagger be able to parse `java.util.Optional`?
Currently, if I don't use scala.Option, the attribute type is `java.util.Optional(boolean)` and it is "required".

**Comment by kailuowang** [comment]
@Flo354 I am open to adding `java.util.Optional`. but I am not sure Play doc recommend using `java.util.Optional` for scala developers. The one you gave is documentation for java developers, the for scala developers version uses scala Option.
