### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ajaimesv** [iheartradio/play-swagger#243]
Hello everyone, 

I keep getting the following error for the following environment: sbt 1.2.8, Scala 2.12.8

My `plugins.sbt` looks like this:

```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.0")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.11.0")
addSbtPlugin("com.iheart" %% "sbt-play-swagger" % "0.7.5-PLAY2.7")
```

and `build.sbt` like:
```
name := """some-name"""
organization := "com.domain"

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala, SwaggerPlugin)

scalaVersion := "2.12.8"

libraryDependencies += guice
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.1" % Test
libraryDependencies += "com.amazonaws" % "aws-java-sdk-dynamodb" % "1.11.475"
libraryDependencies += "org.webjars" % "swagger-ui" % "3.20.5"

swaggerDomainNameSpaces := Seq("models")
```

I have tried changing to different plugin versions but none of them seem to work for me. I found a [similar issue](https://github.com/iheartradio/play-swagger/issues/144) but didn't help.
Any help is very appreciated...

```
[info] Running com.iheart.playSwagger.SwaggerSpecRunner /Users/user/Temp/some-name/target/swagger/swagger.json routes models  false 1.0-SNAPSHOT false
[error] (run-main-0) java.lang.NoSuchMethodError: play.api.libs.json.Reads$.traversableReads(Lscala/collection/generic/CanBuildFrom;Lplay/api/libs/json/Reads;)Lplay/api/libs/json/Reads;
[error] java.lang.NoSuchMethodError: play.api.libs.json.Reads$.traversableReads(Lscala/collection/generic/CanBuildFrom;Lplay/api/libs/json/Reads;)Lplay/api/libs/json/Reads;
[error]         at com.iheart.playSwagger.Domain$CustomTypeMapping$.<init>(Domain.scala:59)
[error]         at com.iheart.playSwagger.Domain$CustomTypeMapping$.<clinit>(Domain.scala)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.customMappings$lzycompute(SwaggerSpecGenerator.scala:263)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.customMappings(SwaggerSpecGenerator.scala:262)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$endPointSpec$4(SwaggerSpecGenerator.scala:372)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:742)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:741)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$endPointSpec$2(SwaggerSpecGenerator.scala:370)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
[error]         at scala.collection.immutable.List.flatMap(List.scala:355)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.endPointSpec(SwaggerSpecGenerator.scala:369)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.endPointEntry(SwaggerSpecGenerator.scala:335)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$paths$1(SwaggerSpecGenerator.scala:312)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
[error]         at scala.collection.immutable.List.flatMap(List.scala:355)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.paths(SwaggerSpecGenerator.scala:312)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutes$1(SwaggerSpecGenerator.scala:127)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutes(SwaggerSpecGenerator.scala:124)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutesFile$16(SwaggerSpecGenerator.scala:109)
[error]         at scala.util.Success.flatMap(Try.scala:251)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutesFile(SwaggerSpecGenerator.scala:108)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:53)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:30)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:36)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:9)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:9)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at sbt.Run.invokeMain(Run.scala:98)
[error]         at sbt.Run.run0(Run.scala:92)
[error]         at sbt.Run.execute$1(Run.scala:68)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:80)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:253)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$13(SwaggerPlugin.scala:49)
[error]         at scala.util.Success.foreach(Try.scala:249)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$12(SwaggerPlugin.scala:49)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (swagger) Nonzero exit code: 1
```

**Comment by kailuowang** [comment]
Might be related to play-json bug, see this https://github.com/iheartradio/play-swagger/issues/239#issuecomment-461817514

**Comment by ajaimesv** [comment]
It worked!

```
libraryDependencies += "com.typesafe.play" %% "play-json" % "2.7.1"
```

Thanks :-)
