### ISSUE TITLE
Unable to create injector - Play 2.7

### ISSUE THREAD

**Issue by mgeeforce** [iheartradio/play-swagger#245]
In trying to implement the "Alternative Setup" I am running into an issue with dependency injection.

Getting the following error:
```
CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: play.routes.compiler.HandlerCall.packageName()Ljava/lang/String;
  at play.modules.swagger.SwaggerPluginImpl.<init>(SwaggerPlugin.scala:35)
  while locating play.modules.swagger.SwaggerPluginImpl
  at play.modules.swagger.SwaggerModule.bindings(SwaggerModule.scala:11):
Binding(interface play.modules.swagger.SwaggerPlugin to ConstructionTarget(class play.modules.swagger.SwaggerPluginImpl) eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)
  while locating play.modules.swagger.SwaggerPlugin
```

I have modified the controller code example for Play 2.7 as follows:

```
package foo

import play.api.Configuration
import com.iheart.playSwagger.SwaggerSpecGenerator
import play.api.libs.json.JsString
import play.api.mvc._
import javax.inject.Inject


class ApiSpecs @Inject()(cc: ControllerComponents, config: Configuration) extends AbstractController(cc) {
  implicit val cl = getClass.getClassLoader

  val domainPackage = "foo.model"
  val swaggerV3 = false;
  lazy val generator = SwaggerSpecGenerator(swaggerV3, domainPackage)

  // Get's host configuration.
  val host = config.get[String]("swagger.host")

  lazy val swagger = Action { request =>
// use routes file with swagger yaml
    generator.generate("swaggerRoutes").map(_ + ("host" -> JsString(host))).fold(
      e => InternalServerError("Couldn't generate swagger."),
      s => Ok(s))
  }

  def specs = swagger
}
```

and am using the following in the build.sbt:

```
  "com.typesafe.play"          %% "play-json"                % "2.7.1"
  "com.iheart"                       %% "play-swagger          % "0.7.5-PLAY2.7"
```

**Comment by mgeeforce** [comment]
fixed quoting

**Comment by kailuowang** [comment]
The error message is complaining `play.modules.swagger.SwaggerModule`, it's not part of play-swagger. Is it from swagger-play? https://github.com/swagger-api/swagger-play/blob/master/play-2.4/swagger-play2/app/play/modules/swagger/SwaggerModule.scala

**Comment by mgeeforce** [comment]
Doh! my bad. I have both swagger-play and play-swagger implemented in the same app to demonstrate the differences regarding annotations in the code, vs in a routes file and to do a bit of a bake-off. looks like there is a conflict.

**Comment by kailuowang** [comment]
Glad it worked out for you. I am going to close it for now.
