### ISSUE TITLE
example fails when using play2.7.0

### ISSUE THREAD

**Issue by marcadella** [iheartradio/play-swagger#247]
In the example/project/plugins.sbt, using:
```
addSbtPlugin("com.typesafe.play" %% "sbt-plugin" % "2.7.0")
addSbtPlugin("com.iheart" %% "sbt-play-swagger" % "0.7.5-PLAY2.7")
```

and then running the sbt swagger command throws the following error:

```
[error] (run-main-0) java.lang.NoSuchMethodError: play.api.libs.json.Reads$.traversableReads(Lscala/collection/generic/CanBuildFrom;Lplay/api/libs/json/Reads;)Lplay/api/libs/json/Reads;
[error] java.lang.NoSuchMethodError: play.api.libs.json.Reads$.traversableReads(Lscala/collection/generic/CanBuildFrom;Lplay/api/libs/json/Reads;)Lplay/api/libs/json/Reads;
[error]         at com.iheart.playSwagger.Domain$CustomTypeMapping$.<init>(Domain.scala:59)
[error]         at com.iheart.playSwagger.Domain$CustomTypeMapping$.<clinit>(Domain.scala)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.customMappings$lzycompute(SwaggerSpecGenerator.scala:263)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.customMappings(SwaggerSpecGenerator.scala:262)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.generateWithBase(SwaggerSpecGenerator.scala:140)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutes(SwaggerSpecGenerator.scala:129)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generateFromRoutesFile$16(SwaggerSpecGenerator.scala:109)
[error]         at scala.util.Success.flatMap(Try.scala:251)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutesFile(SwaggerSpecGenerator.scala:108)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:53)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:30)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:36)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:9)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:9)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:98)
[error]         at sbt.Run.run0(Run.scala:92)
[error]         at sbt.Run.execute$1(Run.scala:68)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:80)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:253)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$13(SwaggerPlugin.scala:49)
[error]         at scala.util.Success.foreach(Try.scala:249)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$12(SwaggerPlugin.scala:49)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (swagger) Nonzero exit code: 1
```

By the way, the example in your 2.7 branch uses play 2.6.

**Comment by kailuowang** [comment]
It needs to add a dependency of play-json 2.7.1
A PR to update the example will be really appreciated.

**Comment by marcadella** [comment]
Cheers, it works fine now. I leave this issue open until the example is updated.
