### ISSUE TITLE
[error] (run-main-0) java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by AminMkh** [iheartradio/play-swagger#277]
When running this plugin, I get the following error:

```[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Running com.iheart.playSwagger.SwaggerSpecRunner /var/www/target/swagger/swagger.json routes models  false 1.0-SNAPSHOT true
[error] (run-main-0) java.nio.charset.MalformedInputException: Input length = 1
[error] java.nio.charset.MalformedInputException: Input length = 1
[error]         at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
[error]         at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
[error]         at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[error]         at java.io.InputStreamReader.read(InputStreamReader.java:184)
[error]         at java.io.BufferedReader.fill(BufferedReader.java:161)
[error]         at java.io.BufferedReader.readLine(BufferedReader.java:324)
[error]         at java.io.BufferedReader.readLine(BufferedReader.java:389)
[error]         at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:74)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:189)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
[error]         at scala.collection.TraversableOnce.to(TraversableOnce.scala:313)
[error]         at scala.collection.TraversableOnce.to$(TraversableOnce.scala:311)
[error]         at scala.collection.AbstractIterator.to(Iterator.scala:1429)
[error]         at scala.collection.TraversableOnce.toList(TraversableOnce.scala:297)
[error]         at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:297)
[error]         at scala.collection.AbstractIterator.toList(Iterator.scala:1429)
[error]         at com.iheart.playSwagger.ResourceReader$.$anonfun$read$1(ResourceReader.scala:19)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at com.iheart.playSwagger.ResourceReader$.read(ResourceReader.scala:19)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$readCfgFile$1(SwaggerSpecGenerator.scala:293)
[error]         at scala.Option.map(Option.scala:163)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.readCfgFile(SwaggerSpecGenerator.scala:286)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$readYmlOrJson$1(SwaggerSpecGenerator.scala:267)
[error]         at scala.Option.orElse(Option.scala:306)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.readYmlOrJson(SwaggerSpecGenerator.scala:267)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.defaultBase$lzycompute(SwaggerSpecGenerator.scala:260)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.defaultBase(SwaggerSpecGenerator.scala:260)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.$anonfun$generate$2(SwaggerSpecGenerator.scala:52)
[error]         at scala.Option.fold(Option.scala:175)
[error]         at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:52)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:30)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:36)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:9)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:9)
[error]         at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:98)
[error]         at sbt.Run.run0(Run.scala:92)
[error]         at sbt.Run.execute$1(Run.scala:68)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:80)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:253)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$13(SwaggerPlugin.scala:49)
[error]         at scala.util.Success.foreach(Try.scala:249)
[error]         at com.iheart.sbtPlaySwagger.SwaggerPlugin$.$anonfun$projectSettings$12(SwaggerPlugin.scala:49)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (swagger) Nonzero exit code: 1
[error] Total time: 21 s, completed Aug 3, 2019 8:59:55 AM
```

Below is my environment:
```
[root@d69927be47f3 www]# java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

scalaVersion := "2.12.8"
sbt version: 1.2.8

Below is my docker build file:

```
FROM centos:latest

# Install Java 8 and 11 on /etc/alternatives to match CentOS VMs and add links
RUN yum install -y java-1.8.0-openjdk-devel
RUN curl -O https://download.oracle.com/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
RUN tar zxvf openjdk-11.0.2_linux-x64_bin.tar.gz
RUN rm openjdk-11.0.2_linux-x64_bin.tar.gz
RUN mkdir -p /etc/alternatives
RUN mv jdk-11.0.2 /etc/alternatives/
RUN ln -s /etc/alternatives/jdk-11.0.2 /etc/alternatives/jdk11
RUN ln -s /etc/alternatives/jdk-11.0.2 /etc/alternatives/jdk-lm

# Install nano, ssh, sshd, NFS client and Git
RUN yum -y install nano openssh-clients openssh-server nfs-utils cifs-utils git wget

# Env variables
ARG SCALA_VERSION
ENV SCALA_VERSION ${SCALA_VERSION:-2.12.7}
ARG SBT_VERSION
ENV SBT_VERSION ${SBT_VERSION:-1.2.8}

# Install SBT
RUN wget http://dl.bintray.com/sbt/rpm/sbt-$SBT_VERSION.rpm
RUN yum install -y sbt-$SBT_VERSION.rpm

# Install Nodejs / NPM
RUN yum install -y gcc-c++ make
RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -
RUN yum install -y nodejs

WORKDIR /var/www
EXPOSE 9000 9443

# Run Script
CMD tail -f /dev/null
```

**Comment by bhavanishankerbelide** [comment]
@AminMkh Is this resolved? if so, can you recall what did you do to fix this?!
