### ISSUE TITLE
Check `play.http.router` configuration value before assuming `routes` as a root file for routes

### ISSUE THREAD

**Issue by mcveat** [iheartradio/play-swagger#36]
My configuration says:

`play.http.router=api.Routes`

Fetching swagger json file fails because `routes` file does not exist on path of my application. Relevant stacktrace:

```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:129)
	at scala.io.BufferedSource.reader(BufferedSource.scala:24)
	at scala.io.BufferedSource.bufferedReader(BufferedSource.scala:25)
	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader$lzycompute(BufferedSource.scala:35)
	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader(BufferedSource.scala:33)
	at scala.io.BufferedSource.scala$io$BufferedSource$$decachedReader(BufferedSource.scala:62)
	at scala.io.BufferedSource$BufferedLineIterator.<init>(BufferedSource.scala:67)
	at scala.io.BufferedSource.getLines(BufferedSource.scala:86)
	at com.iheart.playSwagger.ResourceReader$.read(ResourceReader.scala:11)
	at com.iheart.playSwagger.ResourceReader$.read(ResourceReader.scala:7)
	at com.iheart.playSwagger.RoutesFileReader.com$iheart$playSwagger$RoutesFileReader$$readRoutes(RoutesFileReader.scala:17)
	at com.iheart.playSwagger.RoutesFileReader.readAll(RoutesFileReader.scala:7)
	at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:62)
```

Workaround is to put `routes` file in the `conf` directory with:

```
-> / api.Routes
```

**Comment by joprice** [comment]
This may have been addressed by #48. Can you test with a recent version?

**Comment by pettyjamesm** [comment]
Would it be possible to verify this fix and publish a new version? The latest published release is definitely still impacted the issue.

**Comment by joprice** [comment]
Currently the `generate` method takes a string of the routes file and reads it as a resource from the classpath. You should be able to call it with `generate(api.routes)`. However, I think we could improve this interface by having another method that takes an implicit application and looks up the value of `play.http.router` from the application's configuration. This is likely the most common usage. @kailuowang thoughts?

**Comment by kailuowang** [comment]
@joprice let's see if @pettyjamesm will be okay with the new generate interface (you can read the root routes file name yourself). I would hesitate adding play application as an dependency.

**Comment by pettyjamesm** [comment]
@joprice I'm not sure exactly how that would work. Are you saying that by default it would parse the whole routing tree?

Hooking to the root application router is definitely useful for determining the accurate HTTP paths, but I wouldn't necessarily assume that all routes should be mapped. For instance, my root routes file looks like this:

```
# Misc Non-API routes that serve dashboards, etc
GET /   @controllers.HomeController.index
.... more of these omitted ...

# API docs
GET /docs                       @controllers.ApiDocController.redirectToDocs
GET /docs/swagger.json          @controllers.ApiDocController.fullSpecs
GET /docs/swagger-ui/index.html @controllers.ApiDocController.swaggerHome
GET /docs/swagger-ui/*file      @controllers.ApiDocController.swaggerResource(file)

# API resources
->  /api/v1/charge      charge.Routes
->  /api/v1/cart        cart.Routes
->  /api/v1/inventory   inventory.Routes
->  /api/v1/purchase    purchase.Routes
```

Currently I've made the /docs/swagger.json route call into generate once per sub-route and then I manually merge the generated JSON together and fix the http paths. It kinda works, but it's definitely kludgy. Is that helpful?

**Comment by kailuowang** [comment]
@pettyjamesm , yes by default it will recursively parse the whole tree. 
For now, there are two work around in your case 
1) add `### NoDocs ###` to all the routes you don't want to include. 
or 2) have an api.routes file in which you can have 
```
->  /v1/charge      charge.Routes
->  /v1/cart        cart.Routes
->  /v1/inventory   inventory.Routes
->  /v1/purchase    purchase.Routes
```
And have do `generate("api.routes")` and then add a root path `/api` to your swagger.yml file.

**Comment by pettyjamesm** [comment]
@joprice The 2nd workaround is totally fine with me. I just wanted I way to isolate the API resources from the other routes.

Given that my preferred approach is going to be the second option, I think you can proceed with whatever you'd like for the application router traversal.
