### ISSUE TITLE
Unable To Reference Custom Parameter Definitions

### ISSUE THREAD

**Issue by SattaiLanfear** [iheartradio/play-swagger#80]
I have a base "swagger.yml" defined as:

```yaml
swagger: 2.0
info:
  title: V API
  description: MyServer
  version: 0.7.5
host: "XXX"
schemes:
  - "http"
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  domain:
    name: "X-VirtualDomain"
    in: header
    description: The domain (account) you're attempting to interact with.
    required: true
    type: string
```

When I try to reference the parameter, I get JSON errors.

```raw
###
#   summary: does initial signup for credentials
#   produces:
#     - application/json
#   parameters:
#     - $ref: "#/parameters/domain"
#     - name: email
#       in: body
#       description: The email address to associate with the new account.
#       required: true
#       type: string
#       format: email
#     - name: password
#       in: body
#       description: The password for the new account.
#       required: true
#       type: password
#   responses:
#     200:
#       description: User Created
#       schema:
#         headers:
#           X-Auth-Token:
#             description: An auth token issued to this user
#             type: string
#
#
###
POST    /signup                                    controllers.rest.CredentialsController.signUp


play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[JsResultException: JsResultException(errors:List((,List(ValidationError(List('name' is undefined on object: {"$ref":"#/parameters/domain"}),WrappedArray())))))]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List('name' is undefined on object: {"$ref":"#/parameters/domain"}),WrappedArray())))))
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
        at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
        at play.api.libs.json.JsError.fold(JsResult.scala:13)
        at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
        at play.api.libs.json.JsUndefined.as(JsLookup.scala:137)
        at com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$mergeByName$2.apply(SwaggerSpecGenerator.scala:203)
        at com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$mergeByName$2.apply(SwaggerSpecGenerator.scala:202)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
        at scala.collection.immutable.List.foreach(List.scala:381)
```

**Comment by kailuowang** [comment]
I think you have `- $ref: "#/parameters/domain` in your list of parameters, and json is complaining that it couldn't find the name element in it. Don't know what you trying achieve with that line

**Comment by SattaiLanfear** [comment]
@kailuowang The Swagger Specification allows you to define parameters and several other structures for reuse.  As my api requires that header at... basically every single endpoint, I'd like to avoid copy-pasting it every time.


For an example, I tweaked one of the sample Swagger yaml files to include the parameter:


```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: PetStore on Heroku
  description: |
    **This example has a working backend hosted in Heroku**

    You can try all HTTP operation described in this Swagger spec.
    
    Find source code of this API [here](https://github.com/mohsen1/petstore-api)
host: petstore-api.herokuapp.com
basePath: /pet
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
parameters:
  domain:
    name: "X-VirtualDomain"
    in: header
    description: The domain (account) you're attempting to interact with.
    required: true
    type: string
paths:
  /:
    get:
      parameters:
        - $ref: "#/parameters/domain"
        - name: limit
          in: query
          description: number of pets to return
          type: integer
          default: 11
          minimum: 11
          maximum: 10000
      responses:
        200:
          description:  List all pets
          schema:
            title: Pets
            type: array
            items:
              $ref: '#/definitions/Pet'
    post:
      parameters:
        - $ref: "#/parameters/domain"
        - name: pet
          in: body
          description: The pet JSON you want to post
          schema:
            $ref: '#/definitions/Pet'
          required: true
      responses:
        200:
          description: Make a new pet
    put:
      parameters:
        - $ref: "#/parameters/domain"
        - name: pet
          in: body
          description: The pet JSON you want to post
          schema:
            $ref: '#/definitions/Pet'
          required: true
      responses:
        200:
          description: Updates the pet
  /{petId}:
    get:
      parameters:
        - $ref: "#/parameters/domain"
        - name: petId
          in: path
          type: string
          description: ID of the pet
          required: true
      responses:
        200:
          description: Sends the pet with pet Id

definitions:
  Pet:
    type: object
    properties:
      name:
        type: string
      birthday:
        type: integer
        format: int32
```

If you copy-paste that into http://editor.swagger.io/#/ you can see that swagger accepts parameter references with the same effect as copy-pasting the parameter definition

**Comment by kailuowang** [comment]
I see. this is a bug at the play-swagger side, our json processing doesn't recognize such heterogeneous parameter list.  In particular here is the code that failed 
https://github.com/iheartradio/play-swagger/blob/c198e4463a6962431f2fef621fa6130634ea872b/src/main/scala/com/iheart/playSwagger/SwaggerSpecGenerator.scala#L198-L206
We just need to add a special handling case for such `$ref`. and a test case? 
Contribution will be greatly appreciated. 😃

**Comment by JessePelton** [comment]
The same problem exists for query parameters that are included in the function signature in the routes file. The operation ends up with a parameter definition generated from the signature in the routes file and another defined by the $ref. The Swagger UI seems to detect that there are two definitions for the same parameter and ignores the latter, but I _think_ play-swagger should override the generated definition with the one specified by $ref. This means peering into the reference to obtain the parameter's `name` and `in` values.
I'm new to Scala, Swagger, and Play (and by implication, play-swagger), so I'm not quite sure how to proceed. I guess the first question is whether I should create a new issue.

**Comment by kailuowang** [comment]
@JessePelton your situation is a bit different as you want to override one generated by play-swagger while the original issue is about adding a new one by `$ref`. I wonder if you add the $ref inside the name what happens? 
like 
```yaml
- name: email
  $ref: "#/parameters/email"
```
and in the shared $ref definition you don't define the name. 

If that doesn't work than we will have to change play-swagger to read base yaml before doing the merge, which would not be a trivial change as above.

**Comment by JessePelton** [comment]
Not so workable after all. https://editor.swagger.io/ reports that the generated documentation is invalid because of the additional properties alongside the $ref. Worse, this prevents the swagger-ui "Try it" feature from working.

So...should I create a new issue?

**Comment by kailuowang** [comment]
Yeah a new issue would be great. One solution would be having swagger automatically remove all other attributes after the merge between the comment yaml and the autogenerated yaml if it sees a $ref property.

**Comment by JessePelton** [comment]
See #223.
